export default [
    {   id: 1,
        category: "drafts",
        title: "austin street patina",
        description: false,
        price: 9,
        priceBottle: 16,
    },
    {   id: 2,
        category: "drafts",
        title: "nonsuch red ale",
        description: false,
        price: 9,
        priceBottle: 16,
    },
    {   id: 3,
        category: "drafts",
        title: "allagash white",
        description: false,
        price: 9,
        priceBottle: 16,
    },
    {   id: 4,
        category: "drafts",
        title: "lone pine",
        description: "ask your server for our current selection",
        price: 9,
        priceBottle: 16,
    },
    {   id: 5,
        category: "wine",
        title: "zonin prosecco",
        description: "pair with seafood or salad",
        price: 9,
        priceBottle: 0,
    },
    {   id: 6,
        category: "wine",
        title: "forever young rosé",
        description: "pair with salad, roast, or fish",
        price: 9,
        priceBottle: 33,
    },
    {   id: 7,
        category: "wine",
        title: "yealands sauvignon blanc",
        description: "pair with seafood, chicken, or salad",
        price: 9,
        priceBottle: 32,
    },
    {   id: 8,
        category: "wine",
        title: "hugl-gruner veltliner",
        description: "pair with seafood or a fresh salad",
        price: 10,
        priceBottle: 34,
    },
    {   id: 9,
        category: "wine",
        title: "berceo-rioja",
        description: "pair with spicy food",
        price: 12,
        priceBottle: 47,
    },
    {   id: 10,
        category: "wine",
        title: "crios malbec",
        description: "pair with red meat or rich dessert",
        price: 13,
        priceBottle: 49,
    },
    {   id: 11,
        category: "wine",
        title: "côté mas syrah grenache",
        description: "chilled wine to pair with red meat or cheese",
        price: 8,
        priceBottle: 31,
    },
    {   id: 12,
        category: "wine",
        title: "bogle merlot",
        description: "pair with a wide range of options from a duck to mango sticky rice",
        price: 9,
        priceBottle: 32,
    },
    {   id: 13,
        category: "bottle",
        title: "miller lite",
        description: false,
        price: 5,
        priceBottle: 0,
    },
    {   id: 14,
        category: "bottle",
        title: "twisted tea original",
        description: false,
        price: 5,
        priceBottle: 0,
    },
    {   id: 15,
        category: "bottle",
        title: "peaks ipa",
        description: false,
        price: 5,
        priceBottle: 0,
    },
    {   id: 16,
        category: "bottle",
        title: "corona premier",
        description: false,
        price: 5,
        priceBottle: 0,
    },
    {   id: 17,
        category: "bottle",
        title: "baxter brewing staycation",
        description: false,
        price: 5,
        priceBottle: 0,
    },
    {   id: 18,
        category: "bottle",
        title: "modelo oro",
        description: false,
        price: 5,
        priceBottle: 0,
    },
    {   id: 19,
        category: "bottle",
        title: "truly wild berry",
        description: false,
        price: 6,
        priceBottle: 0,
    },
    {   id: 20,
        category: "bottle",
        title: "singha",
        description: false,
        price: 6,
        priceBottle: 0,
    },
    {   id: 21,
        category: "bottle",
        title: "sapporo",
        description: false,
        price: 6,
        priceBottle: 0,
    },
    {   id: 22,
        category: "bottle",
        title: "jack & coke",
        description: false,
        price: 6,
        priceBottle: 0,
    },
    {   id: 23,
        category: "bottle",
        title: "peaks happy hour",
        description: false,
        price: 6,
        priceBottle: 0,
    },
    {   id: 24,
        category: "bottle",
        title: "kit brewing",
        description: "non-alcoholic",
        price: 7,
        priceBottle: 0,
    },
    {   id: 25,
        category: "bottle",
        title: "baxter seltzer lemon-lime",
        description: false,
        price: 7,
        priceBottle: 0,
    },
    {   id: 26,
        category: "bottle",
        title: "down east original",
        description: false,
        price: 7,
        priceBottle: 0,
    },
    {   id: 27,
        category: "bottle",
        title: "coco vodka lime",
        description: false,
        price: 7,
        priceBottle: 0,
    },
    {   id: 28,
        category: "bottle",
        title: "highnoon pineapple",
        description: false,
        price: 7,
        priceBottle: 0,
    },
    {   id: 29,
        category: "bottle",
        title: "kombucha ginger root",
        description: false,
        price: 7,
        priceBottle: 0,
    },
    {   id: 30,
        category: "beverages",
        title: "soda",
        description: false,
        price: 2,
        priceBottle: 0,
    },
    {   id: 31,
        category: "beverages",
        title: "coffee",
        description: false,
        price: 3,
        priceBottle: 0,
    },
    {   id: 32,
        category: "beverages",
        title: "thai iced tea",
        description: false,
        price: 3.25,
        priceBottle: 0,
    },
]