export default [
    {   id: 1,
        category: "appetizers",
        title: "egg rolls",
        description: "four homemade crisp rolls, taro, vermicelli",
        price: 8,
        vegetarian: true,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 2,
        category: "appetizers",
        title: "spring rolls",
        description: "two rolls, veggies, noodles, mint wrapped in rice paper",
        price: 8,
        vegetarian: true,
        glutenFree: true,
        extraTime: false,
    },
    {   id: 3,
        category: "appetizers",
        title: "crab rangoon",
        description: "five crispy wontons, cream cheese, maine crab meat",
        price: 9,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 4,
        category: "appetizers",
        title: "dumplings",
        description: "six steamed or pan-fried pork dumplings",
        price: 8,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 5,
        category: "appetizers",
        title: "thai sausage",
        description: "spicy, thai herbs, fresh ginger",
        price: 8,
        vegetarian: false, 
        glutenFree: false,
        extraTime: true,
    },
    {   id: 6,
        category: "appetizers",
        title: "chicken satay",
        description: "four marinated chicken skewers",
        price: 9,
        vegetarian: false,
        glutenFree: false,
        extraTime: true,
    },
    {   id: 7,
        category: "appetizers",
        title: "moo ping",
        description: "four marinated pork skewers",
        price: 9,
        vegetarian: false,
        glutenFree: false,
        extraTime: true,
    },
    {   id: 8,
        category: "salads",
        title: "papaya salad",
        description: "green papaya, tomatoes, lime juice, crushed peanuts",
        price: 16,
        vegetarian: false,
        glutenFree: true,
        extraTime: true,
    },
    {   id: 9,
        category: "salads",
        title: "laab gai",
        description: "ground chicken, thai herbs, lime juice, chili",
        price: 18,
        vegetarian: false,
        glutenFree: true,
        extraTime: true,
    },
    {   id: 10,
        category: "salads",
        title: "nahm thok",
        description: "beef or pork tossed in chili, lime, mint, lemongrass",
        price: 19,
        vegetarian: false, 
        glutenFree: true,
        extraTime: true,
    },
    {   id: 11,
        category: "soup",
        title: "tom yum",
        description: "hot and spicy, lemongrass, onions, mushrooms, lime leaves",
        price: 7,
        vegetarian: false,
        glutenFree: true,
        extraTime: false,
    },
    {   id: 12,
        category: "soup",
        title: "tom kha",
        description: "coconut milk, lemongrass, onions, mushrooms",
        price: 7,
        vegetarian: false, 
        glutenFree: true,
        extraTime: false,
    },
    {   id: 13,
        category: "noodles", 
        title: "pad thai",
        description: "egg, scallions, peanuts, bean sprouts",
        price: 0,
        vegetarian: false,
        glutenFree: true,
        extraTime: false,
    },
    {   id: 14,
        category: "noodles",
        title: "ba mee",
        description: "egg noodles, sweet barbecue pork, sprouts tossed in sauce",
        price: 0,
        vegetarian: false,
        glutenFree: true,
        extraTime: false,
    },
    {   id: 15,
        category: "noodles",
        title: "thai lomein",
        description: "egg noodles, broccoli, peppers, carrots, onions",
        price: 0,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 16,
        category: "noodles",
        title: "drunken noodle",
        description: "flat noodles, spicy thai basil, broccoli, peppers, carrots, onions",
        price: 0,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },

    {   id: 17,
        category: "noodles",
        title: "pad se ew",
        description: "flat noodles, broccoli, carrots",
        price: 0,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 18,
        category: "noodles",
        title: "lad nah",
        description: "flat noodles, broccoli, carrots, and mushrooms in homemade gravy",
        price: 0,
        vegetarian: false,
        glutenFree: false,
        extraTime: true,
    },
    {   id: 19,
        category: "signature",
        title: "khao mun gai",
        description: "steamed chicken over seasoned rice with homemade sauce",
        price: 20,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 20,
        category: "signature",
        title: "kanaa moo grob",
        description: "chinese broccoli, carrots, crispy pork",
        price: 23,
        vegetarian: false,
        glutenFree: false,
        extraTime: true,
    },
    {   id: 21,
        category: "signature",
        title: "krah pow moo grob",
        description: "spicy thai basil, green beans, onions, crispy pork",
        price: 23,
        vegetarian: false,
        glutenFree: false,
        extraTime: true,
    },
    {   id: 22,
        category: "entrees",
        title: "krah pow",
        description: "choice of ground pork or chicken, spicy thai basil, sautéed peppers, onions, green beans",
        price: 0,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 23,
        category: "entrees",
        title: "broccoli",
        description: "choice of protein, broccoli, carrots, mushrooms",
        price: 0,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 24,
        category: "entrees",
        title: "cashew",
        description: "choice of protein, carrots, onions, broccoli",
        price: 0,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 25,
        category: "entrees",
        title: "fried rice",
        description: "choice of protein, carrots, onions, broccoli",
        price: 0,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 26,
        category: "entrees",
        title: "garlic",
        description: "choice of protein, broccoli, carrots, onions, mushrooms",
        price: 0,
        vegetarian: false,
        glutenFree: false,
        extraTime: false,
    },
    {   id: 27,
        category: "entrees",
        title: "red curry",
        description: "choice of protein, bamboo, peppers, green beans, basil",
        price: 0,
        vegetarian: false,
        glutenFree: true,
        extraTime: false,
    },
    {   id: 28,
        category: "entrees",
        title: "yellow curry",
        description: "choice of protein, pineapple, potatoes, onions, carrots",
        price: 0,
        vegetarian: false,
        glutenFree: true,
        extraTime: false,
    },
    {   id: 29,
        category: "entrees",
        title: "green curry",
        description: "choice of protein, bamboo, peppers, green beans, basil",
        price: 0, 
        vegetarian: false,
        glutenFree: true,
        extraTime: false,
    },
    {   id: 30,
        category: "entrees",
        title: "panang curry",
        description: "choice of protein, green beans, carrots",
        price: 0,
        vegetarian: false,
        glutenFree: true,
        extraTime: false,
    },
]